/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const ElMess: typeof import('element-plus/es')['ElMess']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
}
