/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/background/index.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColl: typeof import('element-plus/es')['ElColl']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElCollaspe: typeof import('element-plus/es')['ElCollaspe']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Func: typeof import('./src/components/func/index.vue')['default']
    Hitokoto: typeof import('./src/components/hitokoto/index.vue')['default']
    Link: typeof import('./src/components/link/index.vue')['default']
    Links: typeof import('./src/components/links/index.vue')['default']
    Message: typeof import('./src/components/message/index.vue')['default']
    MoreSet: typeof import('./src/components/more-set/index.vue')['default']
    Music: typeof import('./src/components/music/index.vue')['default']
    Player: typeof import('./src/components/player/index.vue')['default']
    Set: typeof import('./src/components/set/index.vue')['default']
    SocialLinks: typeof import('./src/components/social-links/index.vue')['default']
    TimeCapsule: typeof import('./src/components/time-capsule/index.vue')['default']
    Weather: typeof import('./src/components/weather/index.vue')['default']
  }
}
